In [7]:
# import library
import pandas as pd
# uszipcode gives the state&county for each zipcode
from uszipcode import SearchEngine

# we are using the zipcode in "cleaned_population.csv" as the zipcode souce 
# the zipcode inside "cleaned_population.csv" is complete - this csv includes all the zipcode in USA
population_file = "cleaned_population.csv"
pop_df1 = pd.read_csv(population_file)

# Convert Zip Code from numpy.int64 to str
pop_df["zipcode_str"] = pop_df1['zip_code'].apply(lambda x: str(x).zfill(5))

#show the dataframe
pop_df.head()

   popultion zipcode_str
0      17800       00601
1      39716       00602
2      51565       00603
3       6320       00606
4      27976       00610

In [8]:
# create the blank list of state and county to store the data
state = []
county = []

# use counter to the process of the coding process
counter = 0

# Find county and state by zip code
#test_code = pop_df["zipcode_str"]
search = SearchEngine(simple_zipcode=True) # set simple_zipcode=False to use rich info database
for i in pop_df["zipcode_str"]:
    zipcode_data = search.by_zipcode(i)
    
    # convert the data into dictionery
    zipcode_dic = zipcode_data.to_dict()
    
    # store the "state" and "county" from zip dictionary into the lists
    state.append(zipcode_dic["state"])
    county.append(zipcode_dic["county"])
    
    # use the counter to show the storing progress
    counter += 1
    if ((counter % 100) == 0):
        print(f"completed {counter} out of {len(pop_df['zipcode_str'])}")

#store the data into pop_df dataframe
pop_df["state"] = state
pop_df["county"] = county
pop_df.head()

completed 100 out of 33120
completed 200 out of 33120
completed 300 out of 33120
completed 400 out of 33120
completed 500 out of 33120
completed 600 out of 33120
completed 700 out of 33120
completed 800 out of 33120
completed 900 out of 33120
completed 1000 out of 33120
completed 1100 out of 33120
completed 1200 out of 33120
completed 1300 out of 33120
completed 1400 out of 33120
completed 1500 out of 33120
completed 1600 out of 33120
completed 1700 out of 33120
completed 1800 out of 33120
completed 1900 out of 33120
completed 2000 out of 33120
completed 2100 out of 33120
completed 2200 out of 33120
completed 2300 out of 33120
completed 2400 out of 33120
completed 2500 out of 33120
completed 2600 out of 33120
completed 2700 out of 33120
completed 2800 out of 33120
completed 2900 out of 33120
completed 3000 out of 33120
completed 3100 out of 33120
completed 3200 out of 33120
completed 3300 out of 33120
completed 3400 out of 33120
completed 3500 out of 33120
completed 3600 out of 33120
completed 3700 out of 33120
completed 3800 out of 33120
completed 3900 out of 33120
completed 4000 out of 33120
completed 4100 out of 33120
completed 4200 out of 33120
completed 4300 out of 33120
completed 4400 out of 33120
completed 4500 out of 33120
completed 4600 out of 33120
completed 4700 out of 33120
completed 4800 out of 33120
completed 4900 out of 33120
completed 5000 out of 33120
completed 5100 out of 33120
completed 5200 out of 33120
completed 5300 out of 33120
completed 5400 out of 33120
completed 5500 out of 33120
completed 5600 out of 33120
completed 5700 out of 33120
completed 5800 out of 33120
completed 5900 out of 33120
completed 6000 out of 33120
completed 6100 out of 33120
completed 6200 out of 33120
completed 6300 out of 33120
completed 6400 out of 33120
completed 6500 out of 33120
completed 6600 out of 33120
completed 6700 out of 33120
completed 6800 out of 33120
completed 6900 out of 33120
completed 7000 out of 33120
completed 7100 out of 33120
completed 7200 out of 33120
completed 7300 out of 33120
completed 7400 out of 33120
completed 7500 out of 33120
completed 7600 out of 33120
completed 7700 out of 33120
completed 7800 out of 33120
completed 7900 out of 33120
completed 8000 out of 33120
completed 8100 out of 33120
completed 8200 out of 33120
completed 8300 out of 33120
completed 8400 out of 33120
completed 8500 out of 33120
completed 8600 out of 33120
completed 8700 out of 33120
completed 8800 out of 33120
completed 8900 out of 33120
completed 9000 out of 33120
completed 9100 out of 33120
completed 9200 out of 33120
completed 9300 out of 33120
completed 9400 out of 33120
completed 9500 out of 33120
completed 9600 out of 33120
completed 9700 out of 33120
completed 9800 out of 33120
completed 9900 out of 33120
completed 10000 out of 33120
completed 10100 out of 33120
completed 10200 out of 33120
completed 10300 out of 33120
completed 10400 out of 33120
completed 10500 out of 33120
completed 10600 out of 33120
completed 10700 out of 33120
completed 10800 out of 33120
completed 10900 out of 33120
completed 11000 out of 33120
completed 11100 out of 33120
completed 11200 out of 33120
completed 11300 out of 33120
completed 11400 out of 33120
completed 11500 out of 33120
completed 11600 out of 33120
completed 11700 out of 33120
completed 11800 out of 33120
completed 11900 out of 33120
completed 12000 out of 33120
completed 12100 out of 33120
completed 12200 out of 33120
completed 12300 out of 33120
completed 12400 out of 33120
completed 12500 out of 33120
completed 12600 out of 33120
completed 12700 out of 33120
completed 12800 out of 33120
completed 12900 out of 33120
completed 13000 out of 33120
completed 13100 out of 33120
completed 13200 out of 33120
completed 13300 out of 33120
completed 13400 out of 33120
completed 13500 out of 33120
completed 13600 out of 33120
completed 13700 out of 33120
completed 13800 out of 33120
completed 13900 out of 33120
completed 14000 out of 33120
completed 14100 out of 33120
completed 14200 out of 33120
completed 14300 out of 33120
completed 14400 out of 33120
completed 14500 out of 33120
completed 14600 out of 33120
completed 14700 out of 33120
completed 14800 out of 33120
completed 14900 out of 33120
completed 15000 out of 33120
completed 15100 out of 33120
completed 15200 out of 33120
completed 15300 out of 33120
completed 15400 out of 33120
completed 15500 out of 33120
completed 15600 out of 33120
completed 15700 out of 33120
completed 15800 out of 33120
completed 15900 out of 33120
completed 16000 out of 33120
completed 16100 out of 33120
completed 16200 out of 33120
completed 16300 out of 33120
completed 16400 out of 33120
completed 16500 out of 33120
completed 16600 out of 33120
completed 16700 out of 33120
completed 16800 out of 33120
completed 16900 out of 33120
completed 17000 out of 33120
completed 17100 out of 33120
completed 17200 out of 33120
completed 17300 out of 33120
completed 17400 out of 33120
completed 17500 out of 33120
completed 17600 out of 33120
completed 17700 out of 33120
completed 17800 out of 33120
completed 17900 out of 33120
completed 18000 out of 33120
completed 18100 out of 33120
completed 18200 out of 33120
completed 18300 out of 33120
completed 18400 out of 33120
completed 18500 out of 33120
completed 18600 out of 33120
completed 18700 out of 33120
completed 18800 out of 33120
completed 18900 out of 33120
completed 19000 out of 33120
completed 19100 out of 33120
completed 19200 out of 33120
completed 19300 out of 33120
completed 19400 out of 33120
completed 19500 out of 33120
completed 19600 out of 33120
completed 19700 out of 33120
completed 19800 out of 33120
completed 19900 out of 33120
completed 20000 out of 33120
completed 20100 out of 33120
completed 20200 out of 33120
completed 20300 out of 33120
completed 20400 out of 33120
completed 20500 out of 33120
completed 20600 out of 33120
completed 20700 out of 33120
completed 20800 out of 33120
completed 20900 out of 33120
completed 21000 out of 33120
completed 21100 out of 33120
completed 21200 out of 33120
completed 21300 out of 33120
completed 21400 out of 33120
completed 21500 out of 33120
completed 21600 out of 33120
completed 21700 out of 33120
completed 21800 out of 33120
completed 21900 out of 33120
completed 22000 out of 33120
completed 22100 out of 33120
completed 22200 out of 33120
completed 22300 out of 33120
completed 22400 out of 33120
completed 22500 out of 33120
completed 22600 out of 33120
completed 22700 out of 33120
completed 22800 out of 33120
completed 22900 out of 33120
completed 23000 out of 33120
completed 23100 out of 33120
completed 23200 out of 33120
completed 23300 out of 33120
completed 23400 out of 33120
completed 23500 out of 33120
completed 23600 out of 33120
completed 23700 out of 33120
completed 23800 out of 33120
completed 23900 out of 33120
completed 24000 out of 33120
completed 24100 out of 33120
completed 24200 out of 33120
completed 24300 out of 33120
completed 24400 out of 33120
completed 24500 out of 33120
completed 24600 out of 33120
completed 24700 out of 33120
completed 24800 out of 33120
completed 24900 out of 33120
completed 25000 out of 33120
completed 25100 out of 33120
completed 25200 out of 33120
completed 25300 out of 33120
completed 25400 out of 33120
completed 25500 out of 33120
completed 25600 out of 33120
completed 25700 out of 33120
completed 25800 out of 33120
completed 25900 out of 33120
completed 26000 out of 33120
completed 26100 out of 33120
completed 26200 out of 33120
completed 26300 out of 33120
completed 26400 out of 33120
completed 26500 out of 33120
completed 26600 out of 33120
completed 26700 out of 33120
completed 26800 out of 33120
completed 26900 out of 33120
completed 27000 out of 33120
completed 27100 out of 33120
completed 27200 out of 33120
completed 27300 out of 33120
completed 27400 out of 33120
completed 27500 out of 33120
completed 27600 out of 33120
completed 27700 out of 33120
completed 27800 out of 33120
completed 27900 out of 33120
completed 28000 out of 33120
completed 28100 out of 33120
completed 28200 out of 33120
completed 28300 out of 33120
completed 28400 out of 33120
completed 28500 out of 33120
completed 28600 out of 33120
completed 28700 out of 33120
completed 28800 out of 33120
completed 28900 out of 33120
completed 29000 out of 33120
completed 29100 out of 33120
completed 29200 out of 33120
completed 29300 out of 33120
completed 29400 out of 33120
completed 29500 out of 33120
completed 29600 out of 33120
completed 29700 out of 33120
completed 29800 out of 33120
completed 29900 out of 33120
completed 30000 out of 33120
completed 30100 out of 33120
completed 30200 out of 33120
completed 30300 out of 33120
completed 30400 out of 33120
completed 30500 out of 33120
completed 30600 out of 33120
completed 30700 out of 33120
completed 30800 out of 33120
completed 30900 out of 33120
completed 31000 out of 33120
completed 31100 out of 33120
completed 31200 out of 33120
completed 31300 out of 33120
completed 31400 out of 33120
completed 31500 out of 33120
completed 31600 out of 33120
completed 31700 out of 33120
completed 31800 out of 33120
completed 31900 out of 33120
completed 32000 out of 33120
completed 32100 out of 33120
completed 32200 out of 33120
completed 32300 out of 33120
completed 32400 out of 33120
completed 32500 out of 33120
completed 32600 out of 33120
completed 32700 out of 33120
completed 32800 out of 33120
completed 32900 out of 33120
completed 33000 out of 33120
completed 33100 out of 33120

   popultion zipcode_str state               county
0      17800       00601    PR   Adjuntas Municipio
1      39716       00602    PR     Aguada Municipio
2      51565       00603    PR  Aguadilla Municipio
3       6320       00606    PR    Maricao Municipio
4      27976       00610    PR      Aasco Municipio

In [9]:
# store the data in .csv file
pop_df.to_csv("cleaned_zip_population.csv")